### ISSUE TITLE
Inconsistent seasonality tests

### ISSUE THREAD

**Issue by mloning** [Mcompetitions/M4-methods#25]
The seasonality tests in Python and R seem to give different results. 

If you run the R code snippet below, you get FALSE. If you run the Python snippet you get True. 

R code:
```R
# copied from https://github.com/Mcompetitions/M4-SeasonalityTest <- function(input, ppy){
  #Used to determine whether a time series is seasonal
  tcrit <- 1.645
  if (length(input)<3*ppy){
    test_seasonal <- FALSE
  }else{
    xacf <- acf(input, plot = FALSE)$acf[-1, 1, 1]
    clim <- tcrit/sqrt(length(input)) * sqrt(cumsum(c(1, 2 * xacf^2)))
    test_seasonal <- ( abs(xacf[ppy]) > clim[ppy] )
    
    if (is.na(test_seasonal)==TRUE){ test_seasonal <- FALSE }
  }
  
  return(test_seasonal)
}

data <- c(2.62434536, -0.61175641, -0.52817175, -1.07296862,  1.86540763,
          -2.3015387 ,  1.74481176, -0.7612069 ,  1.3190391 , -0.24937038,
          1.46210794, -2.06014071,  0.6775828 , -0.38405435,  1.13376944,
          -1.09989127)
ppy <- 4 
SeasonalityTest(data, ppy)
```

Python code:
```Python
import numpy as np
from math import sqrt
data = np.array([2.62434536, -0.61175641, -0.52817175, -1.07296862,  1.86540763,
-2.3015387 ,  1.74481176, -0.7612069 ,  1.3190391 , -0.24937038,
1.46210794, -2.06014071,  0.6775828 , -0.38405435,  1.13376944,
-1.09989127])

# copied from https://github.com/Mcompetitions/M4-methods/blob/master/ML_benchmarks.py
def seasonality_test(original_ts, ppy):
    """
    Seasonality test
    :param original_ts: time series
    :param ppy: periods per year
    :return: boolean value: whether the TS is seasonal
    """
    s = acf(original_ts, 1)
    for i in range(2, ppy):
        s = s + (acf(original_ts, i) ** 2)

    limit = 1.645 * (sqrt((1 + 2 * s) / len(original_ts)))

    return (abs(acf(original_ts, ppy))) > limit


def acf(data, k):
    """
    Autocorrelation function
    :param data: time series
    :param k: lag
    :return:
    """
    m = np.mean(data)
    s1 = 0
    for i in range(k, len(data)):
        s1 = s1 + ((data[i] - m) * (data[i - k] - m))

    s2 = 0
    for i in range(0, len(data)):
        s2 = s2 + ((data[i] - m) ** 2)

    return float(s1 / s2)

ppy = 4
seasonality_test(data, ppy)
```

The difference is that in the Python code you do not take the square of the autocorrelation coefficient at the first lag, i.e.
```Python
s = acf(original_ts, 1) ** 2
```

**Comment by vangspiliot** [comment]
Hi mloning,

Thanks for mentioning this issue. Indeed, there is a difference between the two tests, with the Python one not using squared ACF1

As I can see, this has a minor impact to the monthly and hourly series, no impact on the yearly/weekly/daily series (no testing is done) and some impact to the quarterly ones. 

We'll leave a comment on the Python code, but won't change it to allow for the results to be reproducible (same as the ones originally used)

**Comment by mloning** [comment]
Yes, that's more or less what I've found too. Could you post a literature reference to the test that you're using?

**Comment by mloning** [comment]
Just to be sure, another difference are these lines: 
```R
  if (length(input)<3*ppy){
    test_seasonal <- FALSE
```

**Comment by mloning** [comment]
You said that it has a minor impact, do you have any numbers for it?

**Comment by Mcompetitions** [comment]
Regarding the difference you mentioned about the two seasonality tests (setting series that contain less than 3 periods of data as non-seasonal) this was done because decompose() works only when three or more seasonal periods are available. This is not the case in Python.

Regarding the numbers you asked for, after performing a quick test, I found out that the two tests differ in 316 quarterly series, 220 monthly and 0 hourly.

**Comment by mloning** [comment]
@Mcompetitions thanks, I'd also really appreciate a literature reference for the test that you're using, I understand that in the end we're not primarily interested in inference but rather use it in an attempt to improve predictive performance, but I'd be interested in some overview of common seasonality tests.

**Comment by vangspiliot** [comment]
The test used in M4 is described in 
_Fiorucci, J., Pellegrini, T., Louzada, F., Petropoulos, F., Koehler, A. (2016) "Models for optimising the theta method and their relationship to state space models", International Journal of Forecasting,
32(4), 1151-1161_.

Other options could involve unit root tests, like the Canova-Hansen, or metrics measuring seasonal strength (see _Wang, X, Smith, KA, Hyndman, RJ (2006) "Characteristic-based clustering for time series data", Data Mining and Knowledge Discovery, 13(3), 335-364_)
